<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="BikramKarisMini" failures="1" tests="12" name="com.akhilsystem_release.test.emr.VisitWiseWebpart" time="113.334" errors="1" timestamp="2024-07-01T17:17:54 IST" skipped="0">
  <testcase classname="com.akhilsystem_release.test.emr.VisitWiseWebpart" name="openAppointment" time="8.792"/>
  <system-out/>
  <testcase classname="com.akhilsystem_release.test.emr.VisitWiseWebpart" name="firstDoctor" time="19.003"/>
  <system-out/>
  <testcase classname="com.akhilsystem_release.test.emr.VisitWiseWebpart" name="secondDoctor" time="15.042"/>
  <system-out/>
  <testcase classname="com.akhilsystem_release.test.emr.VisitWiseWebpart" name="thirdDoctor" time="15.917"/>
  <system-out/>
  <testcase classname="com.akhilsystem_release.test.emr.VisitWiseWebpart" name="closeAppointment" time="3.075"/>
  <system-out/>
  <testcase classname="com.akhilsystem_release.test.emr.VisitWiseWebpart" name="fstDoctorLogin" time="12.131"/>
  <system-out/>
  <testcase classname="com.akhilsystem_release.test.emr.VisitWiseWebpart" name="fillFstDoctorData" time="6.449">
    <error message="Data not updated successfully. Expected message: &#039;Updated Successfully&#039;, but received: " type="com.akhilsystem_release.base.Base$CustomException">
      <![CDATA[com.akhilsystem_release.base.Base$CustomException: Data not updated successfully. Expected message: 'Updated Successfully', but received: 
at com.akhilsystem_release.test.emr.VisitWiseWebpart.fillFstDoctorData(VisitWiseWebpart.java:144)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </error>
  </testcase> <!-- fillFstDoctorData -->
  <system-out/>
  <testcase classname="com.akhilsystem_release.test.emr.VisitWiseWebpart" name="sndDoctorLogin" time="10.645"/>
  <system-out/>
  <testcase classname="com.akhilsystem_release.test.emr.VisitWiseWebpart" name="verifyFstDoctorData" time="3.312">
    <failure message="expected [1729] but found [361210]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [1729] but found [361210]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at com.akhilsystem_release.test.emr.VisitWiseWebpart.verifyFstDoctorData(VisitWiseWebpart.java:161)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- verifyFstDoctorData -->
  <system-out/>
  <testcase classname="com.akhilsystem_release.test.emr.VisitWiseWebpart" name="fillSndDoctorData" time="3.559"/>
  <system-out/>
  <testcase classname="com.akhilsystem_release.test.emr.VisitWiseWebpart" name="trdDoctorLogin" time="11.097"/>
  <system-out/>
  <testcase classname="com.akhilsystem_release.test.emr.VisitWiseWebpart" name="verifySndDoctorData" time="4.312"/>
  <system-out/>
</testsuite> <!-- com.akhilsystem_release.test.emr.VisitWiseWebpart -->
